module: CredentialsFacebook
author: IBM
github_url: https://github.com/KituraKommunity/Kitura-CredentialsFacebook/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, Kitura-CredentialsFacebook.xcodeproj, -target, CredentialsFacebook, LIBRARY_SEARCH_PATHS=.build/debug]

